### ISSUE TITLE
Add Drizzle

### ISSUE THREAD

**Issue by mschuepbach** [svelte-add/svelte-add#298]
[drizzle-orm](https://github.com/drizzle-team/drizzle-orm)

**Comment by manuel3108** [comment]
That sounds like a good solution, giving the user some amount of choice, but not too much. We might need to think if and how we can test this adder.

I want to avoid getting in a state we had with `svelte-add@v1` where changing anything could have resulted in breaking everything without even noticing. I'm not so worried about the cli itself, as these are quite easily testable by hand, but nobody wants to test 7 adders multiplied by x options by hand. We had that in the past, and it was awful.

We should probably be able to test sqlite quite easily, but we might need to check if the same applies for the other providers.

**Comment by benmccann** [comment]
I think the providers all have a common portion of the setup, which is `const db = drizzle(client)` and anything after that. However, creating the client varies for each database. Maybe we can have a `createClient` method which gets filled in with different code based on the client. We could even simplify it further and have only one or two clients instead of three

I think the other part of this is how do we help people setup and test their database locally. I've never used sqllite, so am not sure what's involved there. When using something like postgres I would usually run it on Docker locally so that I don't have to install the database on my machine. It could help to provide a `docker-compose.yml` in this case so that folks don't need to install the database. This is from a project I setup a couple of years ago, so might be slightly outdated, but could be a helpful starting point:

```
version: "3.0"
services:
  postgres:
    image: postgres:12.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  adminer:
    image: adminer
    restart: always
    ports:
      - "4000:8080"
```
