### ISSUE TITLE
Use `dedent`

### ISSUE THREAD

**Issue by benmccann** [svelte-add/svelte-add#418]
### Topic

drizzle

### Version

`main`

### Expected behavior

no extra indentation or newlines

provide a `dedent` util similar to the one that kit uses in `core`. then use it in the drizzle adder and any others that need it

https://github.com/search?q=repo%3Asveltejs%2Fkit%20dedent&type=code

### Actual behavior

`docker-compose.yml` is highly indented:
```

                services:
                  db:
                    image: postgres
                    restart: always
                    ports:
                      - 5432:5432
                    environment:
                
                      POSTGRES_USER: root
                      POSTGRES_PASSWORD: mysecretpassword
                      POSTGRES_DB: local

```

it looks like others are affected as well
