### ISSUE TITLE
Unnecessary new lines added

### ISSUE THREAD

**Issue by benmccann** [svelte-add/svelte-add#482]
### Topic

tailwind

### Version

2.3.4

### Expected behavior

```
@tailwind base;
@tailwind components;
@tailwind utilities;

@import '@fontsource/fira-mono';

:root {
	--font-body: Arial, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu,
		Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
	--font-mono: 'Fira Mono', monospace;
	--color-bg-0: rgb(202, 216, 228);
	--color-bg-1: hsl(209, 36%, 86%);
	--color-bg-2: hsl(224, 44%, 95%);
	--color-theme-1: #ff3e00;
	--color-theme-2: #4075a6;
	--color-text: rgba(0, 0, 0, 0.7);
	--column-width: 42rem;
	--column-margin-top: 4rem;
	font-family: var(--font-body);
	color: var(--color-text);
}
```

### Actual behavior

```
@tailwind base;

@tailwind components;

@tailwind utilities;

@import '@fontsource/fira-mono';

:root {
	--font-body: Arial, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu,
		Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
	--font-mono: 'Fira Mono', monospace;
	--color-bg-0: rgb(202, 216, 228);
	--color-bg-1: hsl(209, 36%, 86%);
	--color-bg-2: hsl(224, 44%, 95%);
	--color-theme-1: #ff3e00;
	--color-theme-2: #4075a6;
	--color-text: rgba(0, 0, 0, 0.7);
	--column-width: 42rem;
	--column-margin-top: 4rem;
	font-family: var(--font-body);
	color: var(--color-text);
}
```

**Comment by manuel3108** [comment]
Potentially related #467

**Comment by AdrianGonz97** [comment]
There are two issues that are present here when you run the tailwind adder on the demo project:

1. the extra newlines that are (mysteriously) added
2. the order in which the `@tailwind` directive is added

currently, if you run the dev server with the following `app.css`:
```css
@tailwind base;

@tailwind components;

@tailwind utilities;

@import '@fontsource/fira-mono';
```
you'll get this warning from Vite:
```bash
[vite:css] @import must precede all other statements (besides @charset or empty @layer)
3  |  @tailwind utilities;
4  |  
5  |  @import "@fontsource/fira-mono";
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6  |  
7  |  :root {
```
however, **everything still works**.

We always want the `@tailwind` directives to be first in the stylesheet, so moving it below all existing imports isn't an option. In the past, the recommendation from Tailwind was to create a `tailwind.css` file, add the `@tailwind` directives there, and add `@import "./tailwind.css"` to the top of the `app.css` file. I've always hated that since it created even more junk files that clutter up directories.

According to the [tailwind documentation](https://tailwindcss.com/docs/functions-and-directives#config) today (in a not so obvious spot), there's another workaround for this that looks to be better. Instead of the using the `@tailwind` directive, we could instead use `@import`:
```css
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
@import '@fontsource/fira-mono';
```
no more warnings, no extra files needed, and I think it _should_ fix the spacing too

**Comment by benmccann** [comment]
I wonder if that order is also required with lightningcss? https://vitejs.dev/guide/features#lightning-css

Tailwind 4 is going to switch to it and there was some discussion of whether vite or vitePreprocess should too

**Comment by AdrianGonz97** [comment]
> Tailwind 4 is going to switch to it and there was some discussion of whether vite or vitePreprocess should too

It looks like Tailwind v4 is going to switch to this `@import` variation instead of the `@tailwind` directive as well: https://tailwindcss.com/blog/tailwindcss-v4-alpha#css-first-configuration, so it'll be the new blessed way of doing things anyway

---

Re: Newline spacing

It looks like the spacing is due to PostCSS preserving newline consistency between the first two nodes. 

If the starting `app.css` contains a single newline between the `@import` and the next rule:
```css
@import "@fontsource/fira-mono";

:root {
	--font-body: Arial, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
		Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
}
...
```
then the resulting `app.css` will be this after the tailwind adder:
```css
@import "tailwindcss/base";

@import "tailwindcss/components";

@import "tailwindcss/utilities";

@import "@fontsource/fira-mono";

:root {
	--font-body: Arial, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
		Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
}
...
```

If we remove the space between the `@import` and the first rule:
```css
@import "@fontsource/fira-mono";
:root {
	--font-body: Arial, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
		Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
}
...
```

then this is what the `app.css` will look like after:
```css
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
@import "@fontsource/fira-mono";

:root {
	--font-body: Arial, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
		Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
}
...
```

So it's entirely dependent on the current state of the stylesheet. Is this something we still want to change? I don't really see an easy way of doing so unless we do string manipulation rather than AST manipulation (postcss provides a `cleanRaws()` method that strips out _all_ new lines, but that's extreme).
